### PR TITLE
Move unimplemented API definitions to new repo

### PR DESCRIPTION
**Pull request by picklenerd**
This PR moved the unimplemented API functions out of the `lock-keeper-client` crate and into a markdown file in the crate root called `api.md`. The entire file is wrapped in a Rust code block so it should be easily viewable from Github.

I updated the documentation at the top of `api.md` to reflect the content of the file.

I'm open to suggestion for better locations for this file. I like that it's front and center here but I think we'll end up with a pretty bloated root directory at some point. This could be a problem we solve later.

### CODE REVIEW

**Comment by indomitableSwan** [comment]
My feeling is that we want to move this API out of the repo entirely. It seems more appropriate to document internally and have this repo reflect our current, iterative development process without the vestiges of our original component-based approach.

**Comment by picklenerd** [comment]
> My feeling is that we want to move this API out of the repo entirely. It seems more appropriate to document internally and have this repo reflect our current, iterative development process without the vestiges of our original component-based approach.

I like that idea too but it would have to go on confluence or a different repo since we can't use gists. Do you have a preference for where it ends up?

**Review by marsella — COMMENTED** [review]
The other things we created at the same time as this API (and which I think are similarly outdated) are `blockchain.rs`, `transaction.rs`, `policy_engine.rs`, and `keys.rs`. Those files mostly contain type definitions and extra documentation for the types used here, and won't make sense in this repo without this API.

I don't have a strong preference re: moving this out of the repo entirely. We could put it in our client's confluence pages along with the issues I flagged offline (#26, #27, #47, #43, #48) that are all about modifications to these methods and types. We could make a separate repo and port these files and issues over there so they are contained and referenceable but not in the way of the rest of our development.

**Comment by indomitableSwan** [comment]
> The other things we created at the same time as this API (and which I think are similarly outdated) are `blockchain.rs`, `transaction.rs`, `policy_engine.rs`, and `keys.rs`. Those files mostly contain type definitions and extra documentation for the types used here, and won't make sense in this repo without this API.
> 
> I don't have a strong preference re: moving this out of the repo entirely. We could put it in our client's confluence pages along with the issues I flagged offline (#26, #27, #47, #43, #48) that are all about modifications to these methods and types. We could make a separate repo and port these files and issues over there so they are contained and referenceable but not in the way of the rest of our development.
> 
> Edit: sorry, I see those are the two options you already suggested. I guess I have a mild preference for a separate repo because it's all code (albeit, not code we're going to run). Github has the option of archiving repos, which puts an explicit warning that the software is not being developed. That might be a good option.

I think Marcella's suggestion of a separate repo makes sense.

**Comment by picklenerd** [comment]
Moved here: https://github.com/boltlabs-inc/tentative-lock-keeper-api

**Review by indomitableSwan — CHANGES_REQUESTED** [review]
This is a good start, but as [Marcella pointed out](https://github.com/boltlabs-inc/key-mgmt/pull/253#pullrequestreview-1127307303), there is other code in this repository that similarly needs to be moved out to the new repo.

**Comment by picklenerd** [comment]
I've updated the other repo with those files and removed them in this PR.

**Review by indomitableSwan — APPROVED** [review]
Thanks! LGTM.

**Pull request merged**
